### ISSUE TITLE
Release notes reporting no changes.

### ISSUE THREAD

**Issue by Chris-Softrams** [MeilCli/bump-release-action#173] opened 2021-01-21 19:54 UTC
## Description
Created a pull request with 1 commit:
```fix: Removed extra file```

After merging the pull request and having this action run. A new release is created, but lists no changes.
![image](https://user-images.githubusercontent.com/69363247/105403499-d1826c00-5bf6-11eb-880a-f2c9d728f9df.png)

If I compare the new release with the previous release I see
![image](https://user-images.githubusercontent.com/69363247/105403141-58831480-5bf6-11eb-9d7a-2fa83752bedb.png)

## Environment

bump-main.yaml
```
release:
  title-prefix: 't0.12-v'
  title-postfix: ' Released!'
  body-title: 'Changed'
  body-when-empty-changes: 'No changes'
  initial-version: '0.0.1'
  tag-prefix: 't0.12-v'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: 'Breaking'
    - replace-prefix: 'feature: '
      new-prefix: 'Feature '
    - replace-prefix: 'change: '
      new-prefix: 'Change '
    - replace-prefix: 'fix: '
      new-prefix: 'Fix '
    - replace-prefix: 'document: '
      new-prefix: 'Document '
    - replace-prefix: 'dependency: '
      new-prefix: 'Dependency '
branch:
  base-branch: 'main'
  version-branch-prefix: 'v'
  version-branch-postfix: ''
  create-major-version-branch: false
  create-minor-version-branch: false
  bump-version-commit-prefix: 'v'
  bump-version-commit-postfix: ''
categories:
  - title: 'Breaking Changes!'
    labels:
      - 'BreakingChange'
    commits:
      - 'breaking:'
    changes-prefix: ':warning: '
  - title: 'Changes'
    labels:
      - 'Feature'
    commits:
      - 'feature:'
    changes-prefix: ':gift: '
  - title: 'Changes'
    labels:
      - Maintenance
    commits:
      - 'change:'
    changes-prefix: ':hammer: '
  - title: 'Bug Fixes'
    labels:
      - 'Bug'
    commits:
      - 'fix:'
    changes-prefix: ':ambulance: '
  - title: 'Changes'
    labels:
      - 'Documentation'
    commits:
      - 'document:'
    changes-prefix: ':blue_book: '
  - title: 'Dependency Updates'
    labels:
      - 'Dependencies'
    skip-label: 'Development'
    commits:
      - 'dependency:'
    changes-prefix: ':green_book: '
bump:
  default: 'patch'
  major:
    labels:
      - 'BreakingChange'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feature:'
```

release-main.yml
```
name: Release

on:
  push:
    branches:
      - main
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
      dry_run:
        description: 'dry run, true or false'
        default: 'false'
      draft:
        description: 'draft, true or false'
        default: 'false'
      pre_release:
        description: 'pre release, true or false'
        default: 'false'
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
      dry_run:
        description: 'dry run, true or false'
        default: 'false'
      draft:
        description: 'draft, true or false'
        default: 'false'
      pre_release:
        description: 'pre release, true or false'
        default: 'false'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: MeilCli/bump-release-action@v1.0.7
        with:
          config_path: '.github/bump-main.yml'
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}
          draft: ${{ github.event.inputs.draft }}
          pre_release: ${{ github.event.inputs.pre_release }}
```

**Comment by MeilCli** [comment] 2021-01-22 01:22
Does Pull Request `#8` contains of its commit?

In changes calculating, skip commit that contains Pull Request. Because In the case of such a Commit, we want to detect the changes by the label of Pull Request.

So, I think expected behavior is that add `Bug` label to the Pull Request `#8`.
(If you want retry, remove `t0.12-v0.0.10` release and tag, and retry action)

**Comment by MeilCli** [comment] 2021-01-30 13:54
@Chris-Softrams 
How was it?

**Comment by amiiit** [comment] 2022-03-16 11:02
@MeilCli thanks for creating and maintaining this action!

So, if I understand correctly, per design, this will ignore the commit message of a merged PR? 

The workflow of my team is to squash and merge a PR, so a PR will always have exactly one commit, which is the change that I would like to see in the release message. Is there a way for me to achieve this? I'm also happy creating a PR for this action to make it possible.

**Comment by MeilCli** [comment] 2022-03-17 01:39
@amiiit 
>  this will ignore the commit message of a merged PR?

Yes, in currently implementation, action will ignore commit message of a merged PR while calculating release note.
If develop by PR flow, I think that will set PR title and labels because release note will have PR title.

But, this implementation is just for me, so I will add option that include/exclude PR commits while calculating release note, later.
Please give me time.

**Closed** 2022-03-17 16:22 UTC
Labels: Bug
